"use client";

import { jsPDF } from "jspdf";
import { buildTimestampedDownloadFileName } from "@/utils/downloadFileName";
import QRCode from "qrcode";
import { ResponsePago } from "@/interfaces/pago.interface";
import { buildPagoVerificationCode } from "@/utils/pagoReciboCodigo";
import type { GymMasterLocale } from "@/i18n/config";
import {
  assertGimnasioBrandingReadyForCommercialDocs,
  getResolvedGimnasioBranding,
} from "@/utils/gimnasioBrandingClient";

type PagoReceiptLocale = GymMasterLocale;

function receiptTx(locale: PagoReceiptLocale, es: string, en: string) {
  return locale === "en" ? en : es;
}

function formatDate(value?: string | null, locale: PagoReceiptLocale = "es") {
  if (!value) return "-";

  const [year, month, day] = value.slice(0, 10).split("-").map(Number);

  if (!year || !month || !day) {
    return value;
  }

  return new Intl.DateTimeFormat(locale === "en" ? "en-US" : "es-AR", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
  }).format(new Date(Date.UTC(year, month - 1, day)));
}

function formatMoney(value?: number | null, locale: PagoReceiptLocale = "es") {
  const number = Number(value ?? 0);

  return new Intl.NumberFormat(locale === "en" ? "en-US" : "es-AR", {
    style: "currency",
    currency: "ARS",
    minimumFractionDigits: locale === "en" ? 2 : 2,
  }).format(Number.isFinite(number) ? number : 0);
}

function translatePaymentValue(locale: PagoReceiptLocale, value?: string | null) {
  if (!value) return "-";

  const normalized = String(value).toLowerCase().trim();

  const dictionary: Record<string, { es: string; en: string }> = {
    stripe: { es: "Stripe", en: "Stripe" },
    efectivo: { es: "Efectivo", en: "Cash" },
    transferencia: { es: "Transferencia", en: "Bank transfer" },
    mercado_pago: { es: "Mercado Pago", en: "Mercado Pago" },
    mercadopago: { es: "Mercado Pago", en: "Mercado Pago" },
    tarjeta_de_debito: { es: "Tarjeta de débito", en: "Debit card" },
    tarjeta_de_credito: { es: "Tarjeta de crédito", en: "Credit card" },
    debit_card: { es: "Tarjeta de débito", en: "Debit card" },
    credit_card: { es: "Tarjeta de crédito", en: "Credit card" },
    pagado: { es: "Pagado", en: "Paid" },
    paid: { es: "Pagado", en: "Paid" },
    pendiente: { es: "Pendiente", en: "Pending" },
    pending: { es: "Pendiente", en: "Pending" },
    cancelado: { es: "Cancelado", en: "Cancelled" },
    cancelled: { es: "Cancelado", en: "Cancelled" },
  };

  const match = dictionary[normalized] ?? dictionary[normalized.replace(/\s+/g, "_")];
  if (match) return locale === "en" ? match.en : match.es;

  return value
    .replace(/_/g, " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function translateBusinessText(locale: PagoReceiptLocale, value?: string | null) {
  if (!value) return "-";
  if (locale !== "en") return value;

  const normalized = String(value);

  const exactDictionary: Record<string, string> = {
    "Pago registrado automáticamente por Stripe.": "Payment automatically registered by Stripe.",
    "Pago registrado automáticamente por Stripe": "Payment automatically registered by Stripe.",
    "pago registrado automáticamente por Stripe.": "Payment automatically registered by Stripe.",
    "pago registrado automáticamente por Stripe": "Payment automatically registered by Stripe.",
  };

  const exactMatch = exactDictionary[normalized.trim()];
  if (exactMatch) return exactMatch;

  return normalized
    .replace(/Recibo emitido por/gi, "Receipt issued by")
    .replace(/Documento generado por Gym Master.?/gi, "Document generated by Gym Master.")
    .replace(/Pago registrado autom[áa]ticamente por Stripe.?/gi, "Payment automatically registered by Stripe.")
    .replace(/registrado autom[áa]ticamente por Stripe.?/gi, "automatically registered by Stripe.")
    .replace(/registrado autom[áa]ticamente/gi, "automatically registered")
    .replace(/por Stripe.?/gi, "by Stripe.")
    .replace(/Cuota mensual/gi, "Monthly fee")
    .replace(/Cuota/gi, "Fee")
    .replace(/Membresía/gi, "Membership")
    .replace(/Membresia/gi, "Membership")
    .replace(/pagos/gi, "payments")
    .replace(/pago/gi, "payment");
}

function formatReceiptDateTime(value: Date, locale: PagoReceiptLocale) {
  return new Intl.DateTimeFormat(locale === "en" ? "en-US" : "es-AR", {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  }).format(value);
}

function getPeriodLabel(pago: ResponsePago, locale: PagoReceiptLocale) {
  const desde = pago.periodo_desde ?? pago.fecha_pago;
  const hasta = pago.periodo_hasta ?? pago.fecha_vencimiento;

  return `${formatDate(desde, locale)} ${receiptTx(locale, "al", "to")} ${formatDate(hasta, locale)}`;
}

function getSocioEmail(pago: ResponsePago) {
  return pago.socio?.email?.trim() || "-";
}

function getVerificationUrl(pago: ResponsePago) {
  const codigo = buildPagoVerificationCode(pago.id);

  if (typeof window === "undefined") {
    return `/api/pagos/${pago.id}/verificar?codigo=${encodeURIComponent(codigo)}`;
  }

  return new URL(
    `/api/pagos/${pago.id}/verificar?codigo=${encodeURIComponent(codigo)}`,
    window.location.origin
  ).toString();
}

async function loadImageAsPngDataUrl(
  src: string,
  maxWidth = 320,
  maxHeight = 320,
  options?: { tintColor?: string }
) {
  return new Promise<string | null>((resolve) => {
    const image = new Image();
    image.crossOrigin = "anonymous";

    image.onload = () => {
      try {
        const ratio = Math.min(maxWidth / image.width, maxHeight / image.height, 1);
        const canvas = document.createElement("canvas");
        canvas.width = Math.max(1, Math.round(image.width * ratio));
        canvas.height = Math.max(1, Math.round(image.height * ratio));

        const ctx = canvas.getContext("2d");
        if (!ctx) {
          resolve(null);
          return;
        }

        ctx.clearRect(0, 0, canvas.width, canvas.height);
        ctx.drawImage(image, 0, 0, canvas.width, canvas.height);

        if (options?.tintColor) {
          ctx.globalCompositeOperation = "source-in";
          ctx.fillStyle = options.tintColor;
          ctx.fillRect(0, 0, canvas.width, canvas.height);
          ctx.globalCompositeOperation = "source-over";
        }

        resolve(canvas.toDataURL("image/png"));
      } catch {
        resolve(null);
      }
    };

    image.onerror = () => resolve(null);
    image.src = src;
  });
}

function addSectionTitle(doc: jsPDF, title: string, x: number, y: number, lineWidth = 55) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10.5);
  doc.setTextColor(15, 23, 42);
  doc.text(title, x, y);

  doc.setDrawColor(2, 168, 225);
  doc.setLineWidth(0.5);
  doc.line(x, y + 2.2, x + lineWidth, y + 2.2);
}

function addField(
  doc: jsPDF,
  label: string,
  value: string,
  x: number,
  y: number,
  width: number
) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.2);
  doc.setTextColor(100, 116, 139);
  doc.text(label.toUpperCase(), x, y);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);

  const lines = doc.splitTextToSize(value || "-", width);
  doc.text(lines, x, y + 5.2);
}

function addStackedField(
  doc: jsPDF,
  label: string,
  value: string,
  x: number,
  y: number,
  width: number
) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(100, 116, 139);
  doc.text(label.toUpperCase(), x, y);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);
  doc.text(doc.splitTextToSize(value || "-", width), x, y + 4.5);
}

function addStatusPill(doc: jsPDF, value: string, locale: PagoReceiptLocale, x: number, y: number) {
  const normalized = value.toLowerCase();
  const isPaid = normalized === "pagado" || normalized === "paid";
  const isCancelled = normalized === "cancelado" || normalized === "cancelled";

  if (isPaid) {
    doc.setFillColor(220, 252, 231);
    doc.setDrawColor(134, 239, 172);
    doc.setTextColor(22, 101, 52);
  } else if (isCancelled) {
    doc.setFillColor(254, 226, 226);
    doc.setDrawColor(252, 165, 165);
    doc.setTextColor(153, 27, 27);
  } else {
    doc.setFillColor(254, 249, 195);
    doc.setDrawColor(253, 224, 71);
    doc.setTextColor(133, 77, 14);
  }

  doc.roundedRect(x, y, 34, 8, 3, 3, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.text(translatePaymentValue(locale, value), x + 17, y + 5.3, { align: "center" });
}

export async function descargarPagoReciboPdf(
  pago: ResponsePago,
  options?: { locale?: PagoReceiptLocale }
) {
  const locale = options?.locale ?? "es";
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 16;
  const codigo = buildPagoVerificationCode(pago.id);
  const verificationUrl = getVerificationUrl(pago);
  const branding = await getResolvedGimnasioBranding();
  assertGimnasioBrandingReadyForCommercialDocs(branding);

  const [logoDataUrl, qrDataUrl] = await Promise.all([
    loadImageAsPngDataUrl(branding.logoUrl, 256, 256).catch(() => null),
    QRCode.toDataURL(verificationUrl, {
      errorCorrectionLevel: "M",
      margin: 1,
      width: 240,
      color: {
        dark: "#0f172a",
        light: "#ffffff",
      },
    }),
  ]);

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 38, "F");

  doc.setFillColor(2, 168, 225);
  doc.rect(0, 38, pageWidth, 2, "F");

  if (logoDataUrl) {
    doc.setFillColor(255, 255, 255);
    doc.roundedRect(margin, 4, 30, 30, 3, 3, "F");
    doc.addImage(logoDataUrl, "PNG", margin + 2, 6, 26, 26);
  } else {
    doc.setFillColor(2, 168, 225);
    doc.circle(margin + 15, 19, 15, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("GM", margin + 15, 22, { align: "center" });
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text(branding.nombre.toUpperCase(), margin + 37, 17, { maxWidth: pageWidth - margin * 2 - 95 });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(203, 213, 225);
  doc.text(branding.subtitulo || receiptTx(locale, "Recibo oficial de pago de cuota", "Official fee payment receipt"), margin + 37, 24, { maxWidth: pageWidth - margin * 2 - 95 });

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(255, 255, 255);
  doc.text(receiptTx(locale, "RECIBO DE PAGO", "PAYMENT RECEIPT"), pageWidth - margin, 16, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(203, 213, 225);
  doc.text(`${receiptTx(locale, "Código", "Code")}: ${codigo}`, pageWidth - margin, 24, { align: "right" });

  let y = 52;

  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 52, 3, 3, "FD");

  addSectionTitle(doc, receiptTx(locale, "Datos del socio", "Member details"), margin + 5, y + 9, 55);
  addStackedField(
    doc,
    receiptTx(locale, "Nombre del socio", "Member name"),
    pago.socio?.nombre_completo ?? "-",
    margin + 5,
    y + 20,
    pageWidth - margin * 2 - 10
  );
  addStackedField(
    doc,
    receiptTx(locale, "ID socio", "Member ID"),
    pago.socio?.id_socio ?? "-",
    margin + 5,
    y + 32,
    pageWidth - margin * 2 - 10
  );
  addStackedField(doc, "Email", getSocioEmail(pago), margin + 5, y + 44, pageWidth - margin * 2 - 10);

  y += 64;

  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(margin, y, pageWidth - margin * 2, 82, 3, 3, "FD");

  addSectionTitle(doc, receiptTx(locale, "Detalle del pago", "Payment details"), margin + 5, y + 9, 55);

  const col1 = margin + 5;
  const col2 = margin + 70;
  const col3 = margin + 133;

  addField(doc, receiptTx(locale, "Cuota abonada", "Paid fee"), translateBusinessText(locale, pago.cuota?.descripcion ?? receiptTx(locale, "Cuota", "Fee")), col1, y + 22, 55);
  addField(doc, receiptTx(locale, "Período cubierto", "Covered period"), getPeriodLabel(pago, locale), col2, y + 22, 54);
  addField(doc, receiptTx(locale, "Meses cubiertos", "Covered months"), `${pago.meses_cubiertos ?? 1}`, col3, y + 22, 38);

  addField(doc, receiptTx(locale, "Fecha de pago", "Payment date"), formatDate(pago.fecha_pago, locale), col1, y + 43, 55);
  addField(doc, receiptTx(locale, "Fecha de vencimiento", "Due date"), formatDate(pago.fecha_vencimiento, locale), col2, y + 43, 54);
  addField(doc, receiptTx(locale, "Medio de pago", "Payment method"), translatePaymentValue(locale, pago.metodo_pago), col3, y + 43, 38);

  addField(doc, receiptTx(locale, "Registrado por", "Registered by"), pago.registrado_por?.nombre ?? "-", col1, y + 64, 55);
  addField(doc, receiptTx(locale, "Observaciones", "Notes"), translateBusinessText(locale, pago.observaciones ?? "-"), col2, y + 64, 54);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.2);
  doc.setTextColor(100, 116, 139);
  doc.text(receiptTx(locale, "ESTADO", "STATUS"), col3, y + 64);
  addStatusPill(doc, pago.estado ?? "pagado", locale, col3, y + 68);

  y += 94;

  const amountBoxX = margin;
  const amountBoxW = 78;
  const verificationBoxX = margin + amountBoxW + 8;
  const verificationBoxW = pageWidth - margin - verificationBoxX;
  const summaryBoxH = 54;

  doc.setFillColor(230, 247, 253);
  doc.setDrawColor(184, 232, 247);
  doc.roundedRect(amountBoxX, y, amountBoxW, summaryBoxH, 3, 3, "FD");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(2, 132, 199);
  doc.text(receiptTx(locale, "TOTAL ABONADO", "TOTAL PAID"), amountBoxX + 6, y + 11);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text(formatMoney(pago.monto_pagado, locale), amountBoxX + 6, y + 25);

  const descuentoMonto = Number(pago.descuento_monto ?? 0);
  const subtotalPago = Number(pago.subtotal ?? 0);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.2);
  doc.setTextColor(71, 85, 105);

  const resumenPago =
    descuentoMonto > 0
      ? `${receiptTx(locale, "Subtotal", "Subtotal")} ${formatMoney(subtotalPago, locale)} · ${receiptTx(locale, "Descuento", "Discount")} ${formatMoney(descuentoMonto, locale)} (${pago.descuento_porcentaje ?? 0}%). ${receiptTx(locale, "Código", "Code")}: ${codigo}`
      : `${receiptTx(locale, "Comprobante emitido por", "Receipt issued by")} ${branding.nombre}. ${receiptTx(locale, "Código", "Code")}: ${codigo}`;

  doc.text(
    doc.splitTextToSize(resumenPago, amountBoxW - 12),
    amountBoxX + 6,
    y + 36
  );

  doc.setFillColor(255, 255, 255);
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(verificationBoxX, y, verificationBoxW, summaryBoxH, 3, 3, "FD");

  doc.addImage(qrDataUrl, "PNG", verificationBoxX + 6, y + 10, 30, 30);

  const verificationTextX = verificationBoxX + 42;
  const verificationTextW = verificationBoxW - 48;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.8);
  doc.setTextColor(15, 23, 42);
  doc.text(receiptTx(locale, "Verificación del comprobante", "Receipt verification"), verificationTextX, y + 12, {
    maxWidth: verificationTextW,
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(71, 85, 105);
  doc.text(
    doc.splitTextToSize(
      receiptTx(
        locale,
        "Escanee el QR desde administración o consulte el código impreso para validar el pago.",
        "Scan the QR from administration or use the printed code to validate the payment."
      ),
      verificationTextW
    ),
    verificationTextX,
    y + 21
  );

  doc.setFont("helvetica", "bold");
  doc.setFontSize(6.5);
  doc.setTextColor(2, 132, 199);
  doc.text(doc.splitTextToSize(codigo, verificationTextW), verificationTextX, y + 42);

  y += 68;

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageWidth - margin, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.2);
  doc.setTextColor(100, 116, 139);
  const legalText = locale === "en"
    ? translateBusinessText(
        locale,
        branding.textoLegalRecibos ||
          `This receipt confirms the administrative payment record in ${branding.nombre}. Operational validity can be verified using the QR code or printed code.`
      )
    : branding.textoLegalRecibos ||
      `Este recibo acredita el registro administrativo del pago en ${branding.nombre}. La validez operativa puede verificarse mediante el QR o código informado.`;

  doc.text(
    doc.splitTextToSize(legalText, pageWidth - margin * 2),
    margin,
    y + 9
  );

  doc.setFontSize(6.8);
  doc.setTextColor(148, 163, 184);
  const footerText = locale === "en"
    ? "Document generated by Gym Master."
    : branding.piePagina;

  doc.text(`${footerText} · ${receiptTx(locale, "Emitido", "Issued")}: ${formatReceiptDateTime(new Date(), locale)}`, margin, pageHeight - 12, { maxWidth: pageWidth - margin * 2 - 45 });
  doc.text(`${receiptTx(locale, "Pago ID", "Payment ID")}: ${pago.id}`, pageWidth - margin, pageHeight - 12, {
    align: "right",
  });

  const filePrefix = locale === "en" ? "receipt-gym-master" : "recibo-gym-master";
  doc.save(buildTimestampedDownloadFileName(`${filePrefix}-${codigo}`, "pdf"));
}
