-- Gym Master local baseline for workout routine migrations
-- Date: 2026-05-20
-- Purpose:
--   Provide the minimum public schema required to run and validate the
--   public.generar_rutina_socio RPC locally with Supabase CLI.
--
-- Important:
--   This baseline is for local reconstruction/testing. The remote Gym Master
--   database already has its schema. Before pushing remote migrations, mark this
--   baseline as applied in the remote migration history and push only pending
--   real changes.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.nivel (
  id_nivel integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_nivel varchar(100) NOT NULL,
  creado_en timestamptz NOT NULL DEFAULT now(),
  actualizado_en timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.objetivo (
  id_objetivo integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_objetivo varchar(100) NOT NULL,
  creado_en timestamp without time zone DEFAULT now(),
  actualizado_en timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.grupo_muscular (
  id_gm integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_gp varchar(100) NOT NULL,
  creado_en timestamp without time zone DEFAULT now(),
  actualizado_en timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.dia (
  id_dia integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_dia varchar(50) NOT NULL,
  creado_en timestamp without time zone DEFAULT now(),
  actualizado_en timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ejercicio (
  id_ejercicio integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_ejercicio varchar(150) NOT NULL,
  id_nivel integer NOT NULL REFERENCES public.nivel(id_nivel),
  id_objetivo integer NOT NULL REFERENCES public.objetivo(id_objetivo),
  id_gm integer NOT NULL REFERENCES public.grupo_muscular(id_gm),
  imagen text,
  creado_en timestamp without time zone DEFAULT now(),
  actualizado_en timestamp without time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.socio (
  id_socio uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id uuid,
  nombre_completo varchar(150) NOT NULL,
  dni varchar(20) UNIQUE,
  direccion text,
  telefono varchar(30),
  activo boolean DEFAULT true,
  fecha_alta date DEFAULT CURRENT_DATE,
  fecha_baja date,
  creado_en timestamp without time zone DEFAULT now(),
  actualizado_en timestamp without time zone DEFAULT now(),
  foto text,
  email varchar(150) UNIQUE,
  nivel integer REFERENCES public.nivel(id_nivel),
  objetivo integer REFERENCES public.objetivo(id_objetivo),
  dias_por_semana integer,
  sexo varchar(20),
  fecnac date,
  descuento_activo boolean DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.rutina (
  id_rutina integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_socio uuid NOT NULL REFERENCES public.socio(id_socio),
  rutina_desc jsonb NOT NULL,
  creado_en timestamp without time zone DEFAULT now(),
  actualizado_en timestamp without time zone DEFAULT now(),
  contenido jsonb,
  semana integer,
  nombre varchar
);

CREATE UNIQUE INDEX IF NOT EXISTS rutina_unq_socio_semana
  ON public.rutina (id_socio, semana);

DROP FUNCTION IF EXISTS public.generar_rutina_socio(uuid, integer, integer, integer);

CREATE FUNCTION public.generar_rutina_socio(p_id_socio uuid, p_id_objetivo integer DEFAULT NULL::integer, p_id_nivel integer DEFAULT NULL::integer, p_dias integer DEFAULT NULL::integer) RETURNS TABLE(id_rutina integer, rutina jsonb)
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'public'
    AS $$
DECLARE
v_objetivo              int;
v_nivel                 int;
v_dias                  int;
v_inicio                date;
v_fin                   date;
v_week                  int;
v_series                int;
v_reps                  text;
v_descanso              int;
v_ejercicios_por_dia    int;
v_grupos_por_dia        int := 2;   -- <<< ahora 2 grupos por día
v_last_used             int[] := ARRAY[]::int[];
v_rotation              int[];
v_rotation_len          int;
v_last_main             int := NULL;
v_primary_gm            int;
v_secondary_gm          int;
v_dias_array            jsonb := '[]'::jsonb;
v_dia_json              jsonb;
v_day_json1             jsonb;
v_day_json2             jsonb;
v_rutina_json           jsonb;
v_id_rutina             int;
v_cnt                   int;
v_pos                   int;
v_primary_pos           int;
v_secondary_pos         int;
v_first_count           int;
v_second_count          int;
i                       int;
k_ventana_no_repetir    interval := interval '45 days';
BEGIN
SELECT
COALESCE(p_id_objetivo, s.objetivo),
COALESCE(p_id_nivel,    s.nivel),
COALESCE(p_dias,        s.dias_por_semana)
INTO v_objetivo, v_nivel, v_dias
FROM socio s
WHERE s.id_socio = p_id_socio;
IF v_objetivo IS NULL OR v_nivel IS NULL OR v_dias IS NULL THEN
RAISE EXCEPTION 'Faltan datos (objetivo, nivel o dias_por_semana) para el socio %', p_id_socio;
END IF;
IF v_objetivo = 4 THEN          -- Fuerza (ejemplo)
v_series   := 5;
v_reps     := '3-5';
v_descanso := 180;
ELSIF v_objetivo = 2 THEN        -- Definición (ejemplo)
v_series   := 3;
v_reps     := '12-15';
v_descanso := 60;
ELSE                              -- Hipertrofia / general
v_series   := 4;
v_reps     := '8-12';
v_descanso := 90;
END IF;
CASE v_nivel
WHEN 1 THEN v_ejercicios_por_dia := 6;  -- Inicial
WHEN 2 THEN v_ejercicios_por_dia := 7;  -- Intermedio
ELSE         v_ejercicios_por_dia := 8; -- Avanzado
END CASE;
v_first_count  := CEIL(v_ejercicios_por_dia / 2.0);
v_second_count := v_ejercicios_por_dia - v_first_count;
v_inicio := (current_date + (8 - extract(isodow from current_date))::int)::date;
IF v_inicio = current_date AND extract(isodow from current_date) = 1 THEN
v_inicio := current_date;
END IF;
v_fin   := v_inicio + (v_dias - 1);
v_week  := EXTRACT(week FROM v_inicio)::int;
SELECT array_agg((e->>'id')::int)
INTO v_last_used
FROM (
SELECT rutina_desc
FROM rutina
WHERE id_socio = p_id_socio
AND creado_en >= (now()::date - k_ventana_no_repetir)
ORDER BY creado_en DESC
LIMIT 1
) r
CROSS JOIN LATERAL jsonb_array_elements(r.rutina_desc->'dias') d
CROSS JOIN LATERAL jsonb_array_elements(d->'ejercicios') e;
IF v_last_used IS NULL THEN
v_last_used := ARRAY[]::int[];
END IF;
SELECT array_agg(gm.id_gm ORDER BY gm.id_gm)
INTO v_rotation
FROM grupo_muscular gm
WHERE EXISTS (
SELECT 1
FROM ejercicio ej
WHERE ej.id_gm = gm.id_gm
AND ej.id_objetivo = v_objetivo
AND ej.id_nivel    = v_nivel
);
v_rotation_len := COALESCE(array_length(v_rotation, 1), 0);
IF v_rotation_len = 0 THEN
RAISE EXCEPTION 'No hay ejercicios definidos para objetivo % y nivel %', v_objetivo, v_nivel;
END IF;
IF v_rotation_len < 2 THEN
v_grupos_por_dia := 1; -- si sólo hay 1 grupo disponible
END IF;
FOR i IN 1..v_dias LOOP
IF v_last_main IS NULL THEN
v_primary_gm := v_rotation[1];
ELSE
v_pos := COALESCE(array_position(v_rotation, v_last_main), 1);
IF v_pos = v_rotation_len THEN
v_primary_gm := v_rotation[1];
ELSE
v_primary_gm := v_rotation[v_pos + 1];
END IF;
END IF;
v_last_main := v_primary_gm;
IF v_grupos_por_dia = 2 THEN
v_primary_pos := COALESCE(array_position(v_rotation, v_primary_gm), 1);
IF v_primary_pos = v_rotation_len THEN
v_secondary_gm := v_rotation[1];
ELSE
v_secondary_gm := v_rotation[v_primary_pos + 1];
END IF;
ELSE
v_secondary_gm := v_primary_gm;
END IF;
WITH pool AS (
SELECT e.id_ejercicio AS id,
e.nombre_ejercicio AS nombre,
e.id_gm AS grupo,
e.imagen
FROM ejercicio e
WHERE e.id_objetivo = v_objetivo
AND e.id_nivel    = v_nivel
AND e.id_gm       = v_primary_gm
AND NOT (e.id_ejercicio = ANY (v_last_used))
ORDER BY random()
LIMIT v_first_count
),
fallback AS (
SELECT e.id_ejercicio AS id,
e.nombre_ejercicio AS nombre,
e.id_gm AS grupo,
e.imagen
FROM ejercicio e
WHERE e.id_objetivo = v_objetivo
AND e.id_nivel    = v_nivel
AND e.id_gm       = v_primary_gm
ORDER BY random()
LIMIT v_first_count
)
SELECT COALESCE(jsonb_agg(
jsonb_build_object(
'id', id,
'nombre', nombre,
'grupo', grupo,
'imagen', imagen,
'series', v_series,
'reps', v_reps,
'descanso_seg', v_descanso
)
), '[]'::jsonb)
INTO v_day_json1
FROM (
SELECT * FROM pool
UNION ALL
SELECT * FROM fallback WHERE NOT EXISTS (SELECT 1 FROM pool)
) x;
IF v_grupos_por_dia = 2 THEN
WITH pool2 AS (
SELECT e.id_ejercicio AS id,
e.nombre_ejercicio AS nombre,
e.id_gm AS grupo,
e.imagen
FROM ejercicio e
WHERE e.id_objetivo = v_objetivo
AND e.id_nivel    = v_nivel
AND e.id_gm       = v_secondary_gm
AND NOT (e.id_ejercicio = ANY (v_last_used))
ORDER BY random()
LIMIT v_second_count
),
fallback2 AS (
SELECT e.id_ejercicio AS id,
e.nombre_ejercicio AS nombre,
e.id_gm AS grupo,
e.imagen
FROM ejercicio e
WHERE e.id_objetivo = v_objetivo
AND e.id_nivel    = v_nivel
AND e.id_gm       = v_secondary_gm
ORDER BY random()
LIMIT v_second_count
)
SELECT COALESCE(jsonb_agg(
jsonb_build_object(
'id', id,
'nombre', nombre,
'grupo', grupo,
'imagen', imagen,
'series', v_series,
'reps', v_reps,
'descanso_seg', v_descanso
)
), '[]'::jsonb)
INTO v_day_json2
FROM (
SELECT * FROM pool2
UNION ALL
SELECT * FROM fallback2 WHERE NOT EXISTS (SELECT 1 FROM pool2)
) y;
ELSE
v_day_json2 := '[]'::jsonb;
END IF;
v_dia_json := COALESCE(v_day_json1, '[]'::jsonb) || COALESCE(v_day_json2, '[]'::jsonb);
SELECT array_cat(v_last_used, array_agg((e->>'id')::int)) INTO v_last_used
FROM jsonb_array_elements(v_dia_json) e;
v_dias_array := v_dias_array || jsonb_build_array(
jsonb_build_object(
'dia', i,
'fecha', (v_inicio + (i - 1))::text,
'grupos',
(SELECT jsonb_agg(gm.nombre_gp)
FROM grupo_muscular gm
WHERE gm.id_gm IN (v_primary_gm, v_secondary_gm)),
'ejercicios', v_dia_json
)
);
END LOOP;
v_rutina_json := jsonb_build_object(
'socio_id', p_id_socio::text,
'objetivo', v_objetivo,
'nivel', v_nivel,
'dias_por_semana', v_dias,
'periodo', jsonb_build_object(
'inicio', v_inicio::text,
'fin',    v_fin::text
),
'dias', v_dias_array,
'metadata', jsonb_build_object(
'generated_at', now() AT TIME ZONE 'UTC',
'rules_version', 2,
'grupos_por_dia', v_grupos_por_dia
)
);
INSERT INTO rutina (id_socio, rutina_desc, semana, nombre, actualizado_en)
VALUES (
p_id_socio,
v_rutina_json,
v_week,
'Rutina auto ' || to_char(now(), 'YYYY-MM-DD HH24:MI'),
now()
)
ON CONFLICT (id_socio, semana)
DO UPDATE
SET rutina_desc   = EXCLUDED.rutina_desc,
actualizado_en = now(),
nombre         = EXCLUDED.nombre
RETURNING rutina.id_rutina INTO v_id_rutina;
RETURN QUERY SELECT v_id_rutina, v_rutina_json;
END;
$$;


COMMIT;
