-- Gym Master
-- Migración: foundation para cuotas, pagos y vencimientos
-- Objetivo:
-- 1) Corregir obtener_evolucion_cuota() evitando ambigüedad en monto.
-- 2) Ampliar public.pago para soportar método, estado, período cubierto y trazabilidad Stripe.
-- 3) Preparar funciones base para consultar estado de cuota por socio y listado general.

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;

-- Tablas mínimas para permitir pruebas locales con Supabase CLI.
-- En remoto, si las tablas ya existen, estas sentencias no alteran la estructura existente.
CREATE TABLE IF NOT EXISTS public.usuario (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre character varying(100),
  email character varying(255),
  password_hash text,
  rol character varying(50),
  activo boolean DEFAULT true,
  creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.socio (
  id_socio uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  usuario_id uuid REFERENCES public.usuario(id) ON DELETE CASCADE,
  nombre_completo character varying(100) NOT NULL,
  dni character varying(50) NOT NULL,
  direccion text,
  telefono character varying(50),
  activo boolean NOT NULL DEFAULT true,
  fecha_alta date DEFAULT CURRENT_DATE,
  fecha_baja date,
  creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  foto text,
  email character varying(255)
);

CREATE TABLE IF NOT EXISTS public.cuota (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  descripcion character varying(255) NOT NULL,
  monto numeric NOT NULL,
  periodo character varying(50),
  fecha_inicio date NOT NULL,
  fecha_fin date NOT NULL,
  creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  activo boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS public.historial_precios_cuota (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_socio uuid REFERENCES public.socio(id_socio),
  precio numeric NOT NULL,
  fecha_inicio date NOT NULL,
  fecha_fin date
);

CREATE TABLE IF NOT EXISTS public.pago (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  socio_id uuid NOT NULL REFERENCES public.socio(id_socio) ON DELETE CASCADE,
  cuota_id uuid NOT NULL REFERENCES public.cuota(id) ON DELETE CASCADE,
  fecha_pago date NOT NULL,
  monto_pagado numeric NOT NULL,
  total numeric,
  registrado_por uuid REFERENCES public.usuario(id) ON DELETE SET NULL,
  creado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  actualizado_en timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  fecha_vencimiento date,
  enviar_email boolean
);

-- Ampliación de public.pago para soportar pagos reales de negocio.
ALTER TABLE public.pago
  ADD COLUMN IF NOT EXISTS periodo_desde date,
  ADD COLUMN IF NOT EXISTS periodo_hasta date,
  ADD COLUMN IF NOT EXISTS meses_cubiertos integer DEFAULT 1,
  ADD COLUMN IF NOT EXISTS metodo_pago character varying(30) DEFAULT 'efectivo',
  ADD COLUMN IF NOT EXISTS estado character varying(30) DEFAULT 'pagado',
  ADD COLUMN IF NOT EXISTS stripe_session_id text,
  ADD COLUMN IF NOT EXISTS stripe_payment_intent_id text,
  ADD COLUMN IF NOT EXISTS observaciones text,
  ADD COLUMN IF NOT EXISTS activo boolean DEFAULT true;

-- Normalización de filas existentes.
UPDATE public.pago
SET
  periodo_desde = COALESCE(periodo_desde, fecha_pago),
  periodo_hasta = COALESCE(periodo_hasta, fecha_vencimiento),
  meses_cubiertos = COALESCE(meses_cubiertos, 1),
  metodo_pago = COALESCE(metodo_pago, 'efectivo'),
  estado = COALESCE(estado, 'pagado'),
  activo = COALESCE(activo, true);

-- Constraints defensivos.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pago_meses_cubiertos_check'
      AND conrelid = 'public.pago'::regclass
  ) THEN
    ALTER TABLE public.pago
      ADD CONSTRAINT pago_meses_cubiertos_check
      CHECK (meses_cubiertos IS NULL OR meses_cubiertos >= 1);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pago_periodo_rango_check'
      AND conrelid = 'public.pago'::regclass
  ) THEN
    ALTER TABLE public.pago
      ADD CONSTRAINT pago_periodo_rango_check
      CHECK (periodo_desde IS NULL OR periodo_hasta IS NULL OR periodo_hasta >= periodo_desde);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pago_metodo_pago_check'
      AND conrelid = 'public.pago'::regclass
  ) THEN
    ALTER TABLE public.pago
      ADD CONSTRAINT pago_metodo_pago_check
      CHECK (metodo_pago IS NULL OR metodo_pago IN ('efectivo', 'stripe', 'transferencia', 'otro'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'pago_estado_check'
      AND conrelid = 'public.pago'::regclass
  ) THEN
    ALTER TABLE public.pago
      ADD CONSTRAINT pago_estado_check
      CHECK (estado IS NULL OR estado IN ('pendiente', 'pagado', 'cancelado', 'fallido', 'reembolsado'));
  END IF;
END $$;

-- Índices para consultas de estado de cuota y dashboard.
CREATE INDEX IF NOT EXISTS idx_pago_socio_periodo_hasta
  ON public.pago (socio_id, periodo_hasta DESC);

CREATE INDEX IF NOT EXISTS idx_pago_socio_fecha_vencimiento
  ON public.pago (socio_id, fecha_vencimiento DESC);

CREATE INDEX IF NOT EXISTS idx_pago_estado_metodo
  ON public.pago (estado, metodo_pago);

CREATE INDEX IF NOT EXISTS idx_pago_stripe_session_id
  ON public.pago (stripe_session_id);

-- Fix de función existente: evita referencia ambigua a monto.
CREATE OR REPLACE FUNCTION public.obtener_evolucion_cuota()
RETURNS TABLE(periodo text, anio integer, mes integer, monto numeric)
LANGUAGE sql
STABLE
AS $$
  SELECT
    TO_CHAR(c.fecha_inicio, 'YYYY-MM')::text AS periodo,
    EXTRACT(YEAR FROM c.fecha_inicio)::integer AS anio,
    EXTRACT(MONTH FROM c.fecha_inicio)::integer AS mes,
    c.monto::numeric AS monto
  FROM public.cuota c
  WHERE c.fecha_inicio >= DATE '2024-09-01'
  ORDER BY c.fecha_inicio;
$$;

-- Estado de cuota para un socio puntual.
CREATE OR REPLACE FUNCTION public.obtener_estado_cuota_socio(p_id_socio uuid)
RETURNS TABLE(
  id_socio uuid,
  nombre_completo character varying,
  activo boolean,
  ultimo_pago date,
  ultimo_vencimiento date,
  periodo_hasta date,
  estado_cuota text,
  dias_vencido integer,
  metodo_pago character varying,
  meses_cubiertos integer
)
LANGUAGE sql
STABLE
AS $$
  WITH ultimo AS (
    SELECT p.*
    FROM public.pago p
    WHERE p.socio_id = p_id_socio
      AND COALESCE(p.activo, true) = true
      AND COALESCE(p.estado, 'pagado') = 'pagado'
    ORDER BY
      COALESCE(p.periodo_hasta, p.fecha_vencimiento, p.fecha_pago) DESC,
      p.fecha_pago DESC,
      p.creado_en DESC
    LIMIT 1
  )
  SELECT
    s.id_socio,
    s.nombre_completo,
    s.activo,
    u.fecha_pago AS ultimo_pago,
    u.fecha_vencimiento AS ultimo_vencimiento,
    COALESCE(u.periodo_hasta, u.fecha_vencimiento) AS periodo_hasta,
    CASE
      WHEN u.id IS NULL THEN 'sin_pagos'
      WHEN COALESCE(u.periodo_hasta, u.fecha_vencimiento) < CURRENT_DATE THEN 'vencido'
      ELSE 'al_dia'
    END AS estado_cuota,
    CASE
      WHEN u.id IS NULL THEN 0
      WHEN COALESCE(u.periodo_hasta, u.fecha_vencimiento) < CURRENT_DATE
        THEN (CURRENT_DATE - COALESCE(u.periodo_hasta, u.fecha_vencimiento))::integer
      ELSE 0
    END AS dias_vencido,
    u.metodo_pago,
    u.meses_cubiertos
  FROM public.socio s
  LEFT JOIN ultimo u ON true
  WHERE s.id_socio = p_id_socio;
$$;

-- Estado de cuota para dashboard/listado general.
CREATE OR REPLACE FUNCTION public.obtener_socios_estado_cuota()
RETURNS TABLE(
  id_socio uuid,
  nombre_completo character varying,
  activo boolean,
  ultimo_pago date,
  ultimo_vencimiento date,
  periodo_hasta date,
  estado_cuota text,
  dias_vencido integer,
  metodo_pago character varying,
  meses_cubiertos integer
)
LANGUAGE sql
STABLE
AS $$
  WITH ultimo AS (
    SELECT DISTINCT ON (p.socio_id)
      p.*
    FROM public.pago p
    WHERE COALESCE(p.activo, true) = true
      AND COALESCE(p.estado, 'pagado') = 'pagado'
    ORDER BY
      p.socio_id,
      COALESCE(p.periodo_hasta, p.fecha_vencimiento, p.fecha_pago) DESC,
      p.fecha_pago DESC,
      p.creado_en DESC
  )
  SELECT
    s.id_socio,
    s.nombre_completo,
    s.activo,
    u.fecha_pago AS ultimo_pago,
    u.fecha_vencimiento AS ultimo_vencimiento,
    COALESCE(u.periodo_hasta, u.fecha_vencimiento) AS periodo_hasta,
    CASE
      WHEN u.id IS NULL THEN 'sin_pagos'
      WHEN COALESCE(u.periodo_hasta, u.fecha_vencimiento) < CURRENT_DATE THEN 'vencido'
      ELSE 'al_dia'
    END AS estado_cuota,
    CASE
      WHEN u.id IS NULL THEN 0
      WHEN COALESCE(u.periodo_hasta, u.fecha_vencimiento) < CURRENT_DATE
        THEN (CURRENT_DATE - COALESCE(u.periodo_hasta, u.fecha_vencimiento))::integer
      ELSE 0
    END AS dias_vencido,
    u.metodo_pago,
    u.meses_cubiertos
  FROM public.socio s
  LEFT JOIN ultimo u ON u.socio_id = s.id_socio
  ORDER BY estado_cuota DESC, s.nombre_completo ASC;
$$;
